// Configuration for YTPlayer
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25000;
var channelName = "lynn_doesnt_pray";
var auth="ziimHhwwEvvT9yGeKHtAWI6P3o45Cr";
var http="https://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
